/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bwck_cloudAIO_ndkTest_NativeInterface */

#ifndef _Included_com_bwck_cloudAIO_ndkTest_NativeInterface
#define _Included_com_bwck_cloudAIO_ndkTest_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bwck_cloudAIO_ndkTest_NativeInterface
 * Method:    Count
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bwck_cloudAIO_ndkTest_NativeInterface_Count
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
